version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - app-network
    ports:
      - "5601:5601"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app-network
    ports:
      - "5000:5000"

  frontend:
    image: kilas-frontend:latest
    container_name: frontend
    networks:
      - app-network
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_BACKEND_URL=http://backend:5000

volumes:
  esdata:
    driver: local

networks:
  app-network:
    driver: bridge