version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
      - "ES_PORT=127.0.0.1:9200"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    restart: always
    networks:
      - docker_elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_HOST=0.0.0.0"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge

volumes:
  elasticsearch_data:
