# Use an official Python runtime as a parent image
FROM python:3.10.6-slim-bullseye
# Set the working directory to /app

COPY . /app
WORKDIR /app
RUN ls
RUN pip install --upgrade pip
RUN pip install -r r.txt

EXPOSE 5000
ENV FLASK_APP=app.py
# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0"]