FROM python:3.10.11-bullseye
# Create a new directory for the project
WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install -r r.txt

EXPOSE 5000
# Start the application
CMD [ "python", "app.py" ]